Repository JuliaManifolds/Manifolds.jl, pull requests merged in 2020-08, with the labels that each got.

#207 Changes power and product manifold to return `CompositeException`s.
  src/manifolds/PowerManifold.jl
  src/manifolds/ProductManifold.jl
  test/multinomial_matrices.jl
  test/oblique.jl
  test/power_manifold.jl
  test/product_manifold.jl
  test/torus.jl
Labels: Ready-for-Review

#209 A little rework do reactivate Julia 1.0 tests
  .github/workflows/ci.yml
  Project.toml
  src/manifolds/PowerManifold.jl
  src/manifolds/ProductManifold.jl
  src/manifolds/SymmetricPositiveSemidefiniteFixedRank.jl
  test/grassmann.jl
  test/runtests.jl
Labels: Ready-for-Review

#208 More Multinomial manifolds: Double Stochastic and Symmetric Multinomial Manifold
  Project.toml
  docs/Project.toml
  docs/make.jl
  docs/src/manifolds/multinomialdoublystochastic.md
  docs/src/manifolds/multinomialsymmetric.md
  src/Manifolds.jl
  src/manifolds/Multinomial.jl
  src/manifolds/MultinomialDoublyStochastic.jl
  src/manifolds/MultinomialSymmetric.jl
  test/grassmann.jl
  test/multinomial_doubly_stochastic.jl
  test/multinomial_matrices.jl
  test/multinomial_symmetric.jl
  test/runtests.jl
Labels: Ready-for-Review, new manifold

#210 Proper errors on Power and Product
  docs/src/features/utilities.md
  src/Manifolds.jl
  src/errors.jl
  src/manifolds/MultinomialDoublyStochastic.jl
  src/manifolds/PowerManifold.jl
  src/manifolds/ProductManifold.jl
  test/errors.jl
  test/groups/group_operation_action.jl
  test/groups/groups_general.jl
  test/multinomial_doubly_stochastic.jl
  test/multinomial_matrices.jl
  test/multinomial_symmetric.jl
  test/oblique.jl
  test/power_manifold.jl
  test/product_manifold.jl
  test/runtests.jl
  test/torus.jl
Labels: Ready-for-Review

#212 Projection on power manifolds
  Project.toml
  src/manifolds/PowerManifold.jl
  test/power_manifold.jl
Labels: Ready-for-Review, extend manifold
