Repository JuliaManifolds/Manifolds.jl, pull requests merged in 2020-04, with the labels that each got.

#139 generalize the sphere manifold to the complex case and to unit norm matrices
  Project.toml
  docs/src/manifolds/sphere.md
  src/Manifolds.jl
  src/manifolds/Euclidean.jl
  src/manifolds/Oblique.jl
  src/manifolds/Rotations.jl
  src/manifolds/Sphere.jl
  src/manifolds/VectorBundle.jl
  src/projected_distribution.jl
  test/oblique.jl
  test/power_manifold.jl
  test/product_manifold.jl
  test/rotations.jl
  test/sphere.jl
  test/vector_bundle.jl
Labels: Ready-for-Review, new manifold

#151 Introduce the manifold of the probability simplex
  Project.toml
  docs/make.jl
  docs/src/manifolds/multinomial.md
  docs/src/manifolds/probabilitysimplex.md
  src/Manifolds.jl
  src/manifolds/Multinomial.jl
  src/manifolds/Oblique.jl
  src/manifolds/ProbabilitySimplex.jl
  src/manifolds/Sphere.jl
  test/multinomial_matrices.jl
  test/oblique.jl
  test/probability_simplex.jl
  test/runtests.jl
Labels: new manifold

#168 get_component and set_component!
  Project.toml
  docs/src/manifolds/power.md
  src/Manifolds.jl
  src/manifolds/PowerManifold.jl
  src/manifolds/ProductManifold.jl
  src/product_representations.jl
  test/power_manifold.jl
  test/product_manifold.jl
  test/runtests.jl
  test/utils.jl
Labels: Ready-for-Review

#169 A small PR to extend vector transport to product & power
  Project.toml
  src/Manifolds.jl
  src/manifolds/Grassmann.jl
  src/manifolds/PowerManifold.jl
  src/manifolds/ProductManifold.jl
  src/manifolds/Sphere.jl
  test/grassmann.jl
  test/power_manifold.jl
  test/product_manifold.jl
  test/sphere.jl
  test/vector_bundle.jl
Labels: Ready-for-Review

#179 Provide get/setindex for Power and Product manifold.
  Project.toml
  src/manifolds/PowerManifold.jl
  src/manifolds/ProductManifold.jl
  test/power_manifold.jl
  test/product_manifold.jl
  test/runtests.jl
Labels: Ready-for-Review
