Repository JuliaManifolds/Manifolds.jl, pull requests merged in 2021-09, with the labels that each got.

#419 Action of rotation around axis and real circle group
  Project.toml
  src/Manifolds.jl
  src/groups/circle_group.jl
  src/groups/group.jl
  src/groups/rotation_action.jl
  src/manifolds/SkewHermitian.jl
  src/tests/tests_group.jl
  test/groups/circle_group.jl
  test/groups/group_operation_action.jl
  test/groups/groups_general.jl
  test/groups/rotation_action.jl
  test/groups/translation_action.jl
Labels: preview docs

#421 `ArrayPartition` as a product manifold representation
  Project.toml
  src/Manifolds.jl
  src/groups/semidirect_product_group.jl
  src/groups/special_euclidean.jl
  src/manifolds/ProductManifold.jl
  src/manifolds/Sphere.jl
  src/product_representations.jl
  test/ambiguities.jl
  test/groups/special_euclidean.jl
  test/manifolds/product_manifold.jl
Labels: Ready-for-Review

#423 Sketch change metric.
  Project.toml
  src/Manifolds.jl
  src/groups/group.jl
  src/manifolds/CenteredMatrices.jl
  src/manifolds/GeneralizedGrassmann.jl
  src/manifolds/Hyperbolic.jl
  src/manifolds/HyperbolicHyperboloid.jl
  src/manifolds/HyperbolicPoincareBall.jl
  src/manifolds/MetricManifold.jl
  src/manifolds/Multinomial.jl
  src/manifolds/PositiveNumbers.jl
  src/manifolds/PowerManifold.jl
  src/manifolds/ProbabilitySimplex.jl
  src/manifolds/ProductManifold.jl
  src/manifolds/Spectrahedron.jl
  src/manifolds/Sphere.jl
  src/manifolds/SymmetricPositiveDefiniteLinearAffine.jl
  src/riemannian_diff.jl
  test/manifolds/generalized_grassmann.jl
  test/manifolds/hyperbolic.jl
  test/manifolds/positive_numbers.jl
  test/manifolds/power_manifold.jl
  test/manifolds/probability_simplex.jl
  test/manifolds/product_manifold.jl
  test/manifolds/sphere.jl
  test/manifolds/symmetric_positive_definite.jl
  test/metric.jl
Labels: Ready-for-Review, preview docs

#430 Introduces vector transport by projection on FixedRankMatrices.
  src/manifolds/FixedRankMatrices.jl
  test/manifolds/fixed_rank.jl
Labels: Ready-for-Review, preview docs
