Repository JuliaManifolds/Manifolds.jl, pull requests merged in 2022-05, with the labels that each got.

#472 Diagonalizing ONB for rotations
  Project.toml
  src/manifolds/Rotations.jl
  test/manifolds/rotations.jl
Labels: Ready-for-Review

#475 Introduce Heisenberg group
  Project.toml
  docs/src/manifolds/group.md
  src/Manifolds.jl
  src/groups/heisenberg.jl
  test/groups/heisenberg.jl
  test/runtests.jl
Labels: new manifold, Ready-for-Review, preview docs

#478 Add a dark mode logo and adapt readme
  README.md
  docs/src/assets/logo-text-readme-dark.png
Labels: Ready-for-Review

#474 Introduce Bures-Wasserstein and Generalised Bures-Wasserstein Metrics
  Project.toml
  docs/src/manifolds/symmetricpositivedefinite.md
  src/Manifolds.jl
  src/groups/connections.jl
  src/manifolds/CholeskySpace.jl
  src/manifolds/SymmetricPositiveDefiniteBuresWasserstein.jl
  src/manifolds/SymmetricPositiveDefiniteGeneralizedBuresWasserstein.jl
  test/ambiguities.jl
  test/manifolds/symmetric_positive_definite.jl
Labels: extend manifold, Ready-for-Review, preview docs

#482 Stabilise log for BW and GBW
  Project.toml
  src/manifolds/SymmetricPositiveDefiniteBuresWasserstein.jl
  src/manifolds/SymmetricPositiveDefiniteGeneralizedBuresWasserstein.jl
Labels: Ready-for-Review
