Repository JuliaManifolds/Manifolds.jl, pull requests merged in 2023-04, with the labels that each got.

#589 Replace PyPlot with PythonPlot
  docs/Project.toml
  docs/make.jl
  docs/src/manifolds/sphere.md
Labels: Ready-for-Review, preview docs

#587 Performance improvements for Stiefel, Grassmann, and generalized variants
  Project.toml
  src/manifolds/GeneralizedGrassmann.jl
  src/manifolds/GeneralizedStiefel.jl
  src/manifolds/Grassmann.jl
  src/manifolds/GrassmannStiefel.jl
  src/manifolds/Stiefel.jl
  test/manifolds/grassmann.jl
  test/manifolds/stiefel.jl
Labels: preview docs

#592 Fix defaults on Grassmann
  Project.toml
  src/manifolds/Grassmann.jl
  test/manifolds/grassmann.jl
Labels: Ready-for-Review
