Repository JuliaManifolds/Manifolds.jl, pull requests merged in 2023-06, with the labels that each got.

#622 💡
  .github/workflows/IntegrationTest.yml
  .github/workflows/ci.yml
  .github/workflows/documenter.yml
  .github/workflows/format.yml
  .github/workflows/nightly.yml
  .gitignore
  _quarto.yml
  docs/CondaPkg.toml
  docs/Project.toml
  docs/make.jl
  docs/src/manifolds/connection.md
  docs/src/manifolds/euclidean.md
  docs/src/manifolds/group.md
  docs/src/manifolds/power.md
  docs/src/manifolds/product.md
  docs/src/manifolds/quotient.md
  docs/src/manifolds/sphere.md
  docs/src/manifolds/symmetricpositivedefinite.md
  docs/src/manifolds/vector_bundle.md
  tutorials/.gitignore
  tutorials/Project.toml
  tutorials/_quarto.yml
  tutorials/getstarted.jl
  tutorials/getstarted.qmd
Labels: restructure, Ready-for-Review, preview docs

#623 Move ManifoldDiff extension here
  Project.toml
  src/Manifolds.jl
  src/groups/group.jl
  src/manifolds/Circle.jl
  src/manifolds/Euclidean.jl
  src/manifolds/Hyperbolic.jl
  src/manifolds/ProductManifold.jl
  src/manifolds/Sphere.jl
  test/groups/special_orthogonal.jl
  test/manifolds/circle.jl
  test/manifolds/euclidean.jl
  test/manifolds/hyperbolic.jl
  test/manifolds/product_manifold.jl
  test/manifolds/sphere.jl
  test/utils.jl
Labels: preview docs

#627 Fix change_metric, change_representer and project for ProbabilitySimplex
  src/manifolds/ProbabilitySimplex.jl
  test/manifolds/probability_simplex.jl
Labels: Ready-for-Review, preview docs

#626 Add Exports, Improve GHA Caches.
  .github/workflows/documenter.yml
  docs/src/manifolds/probabilitysimplex.md
  src/Manifolds.jl
  src/manifolds/ProbabilitySimplex.jl
Labels: Ready-for-Review, preview docs

#629 SPD Fixed Determinant (Isochoric Matrices)
  docs/make.jl
  docs/src/manifolds/spdfixeddeterminant.md
  src/Manifolds.jl
  src/manifolds/SPDFixedDeterminant.jl
  src/manifolds/SymmetricPositiveDefinite.jl
  test/manifolds/spd_fixed_determinant.jl
  test/runtests.jl
Labels: new manifold, Ready-for-Review, preview docs

#604 add `rand` for `ProbabilitySimplex`
  src/Manifolds.jl
  src/manifolds/ProbabilitySimplex.jl
  src/manifolds/ProbabilitySimplexEuclideanMetric.jl
  test/manifolds/probability_simplex.jl
Labels: preview docs

#636 Fix `Rotations(1)`
  Project.toml
  src/manifolds/GeneralUnitaryMatrices.jl
  test/manifolds/rotations.jl
Labels: Ready-for-Review
