Repository JuliaManifolds/Manifolds.jl, pull requests merged in 2023-10, with the labels that each got.

#655 Improve performance of selected operations on SE(n)
  Project.toml
  src/groups/special_euclidean.jl
  src/manifolds/GeneralUnitaryMatrices.jl
  test/groups/special_euclidean.jl
Labels: Ready-for-Review

#662 Introduction of the orthographic retraction for the fixed rank manifold
  .zenodo.json
  NEWS.md
  Project.toml
  docs/src/references.bib
  ext/ManifoldsTestExt/tests_general.jl
  src/Manifolds.jl
  src/manifolds/FixedRankMatrices.jl
  test/manifolds/fixed_rank.jl
Labels: Ready-for-Review

#666 Fix #665
  NEWS.md
  Project.toml
  src/groups/GroupManifold.jl
  src/groups/general_unitary_groups.jl
  src/groups/translation_group.jl
  test/groups/general_unitary_groups.jl
  test/groups/special_euclidean.jl
  test/groups/translation_group.jl
Labels: Ready-for-Review, preview docs

#670 Add `get_embedding` for `GeneralUnitaryMultiplicationGroup`
  .github/workflows/changelog.yml
  .gitignore
  NEWS.md
  Project.toml
  src/groups/general_unitary_groups.jl
  src/groups/special_orthogonal.jl
  test/groups/special_orthogonal.jl
Labels: extend manifold, Ready-for-Review

#672 Update for BoundaryValueDiffEq v5
  NEWS.md
  Project.toml
  ext/ManifoldsBoundaryValueDiffEqExt.jl
Labels: Ready-for-Review
