Repository JuliaManifolds/Manifolds.jl, pull requests merged in 2023-05, with the labels that each got.

#561 Initial work on flag manifold
  Project.toml
  docs/make.jl
  docs/src/manifolds/flag.md
  src/Manifolds.jl
  src/manifolds/FixedRankMatrices.jl
  src/manifolds/Flag.jl
  src/manifolds/FlagOrthogonal.jl
  src/manifolds/FlagStiefel.jl
  src/manifolds/Grassmann.jl
  test/manifolds/flag.jl
  test/runtests.jl
Labels: new manifold, Ready-for-Review, preview docs

#608 Add optional boundary to probability simplex
  Project.toml
  src/manifolds/ProbabilitySimplex.jl
  test/manifolds/probability_simplex.jl
Labels: extend manifold, Ready-for-Review, preview docs

#610 rand for GL and Heisenberg group
  .github/workflows/ci.yml
  Project.toml
  src/groups/general_linear.jl
  src/groups/heisenberg.jl
  src/groups/semidirect_product_group.jl
  test/groups/general_linear.jl
  test/groups/heisenberg.jl
  test/groups/semidirect_product_group.jl
Labels: extend manifold, Ready-for-Review

#614 Fix #613
  Project.toml
  src/groups/group.jl
  test/groups/special_orthogonal.jl
Labels: Ready-for-Review

#619 Deprecate LinearAffineMetric, resolves #527
  .gitignore
  Project.toml
  benchmark/benchmarks.jl
  docs/src/manifolds/symmetricpositivedefinite.md
  src/Manifolds.jl
  src/deprecated.jl
  src/manifolds/SymmetricPositiveDefinite.jl
  src/manifolds/SymmetricPositiveDefiniteAffineInvariant.jl
  test/manifolds/sphere.jl
  test/manifolds/symmetric_positive_definite.jl
  test/runtests.jl
  test/statistics.jl
  test/test_deprecated.jl
  tutorials/getstarted.jl
Labels: Ready-for-Review, preview docs

#615 Reduce TTFisapprox on ProductGroup
  src/groups/product_group.jl
Labels: Ready-for-Review

#612 Make ArrayPartition default instead of ProductRepr
  Project.toml
  src/groups/product_group.jl
  src/groups/semidirect_product_group.jl
  src/groups/special_euclidean.jl
  src/manifolds/Circle.jl
  src/manifolds/ProductManifold.jl
  src/manifolds/VectorBundle.jl
  src/product_representations.jl
  test/groups/metric.jl
  test/groups/semidirect_product_group.jl
  test/groups/special_euclidean.jl
  test/manifolds/circle.jl
  test/manifolds/power_manifold.jl
  test/manifolds/product_manifold.jl
Labels: Ready-for-Review, preview docs

#620 Fix ArrayPartition allocation with (number) eltype
  Project.toml
  src/product_representations.jl
  test/manifolds/product_manifold.jl
Labels: Ready-for-Review
