Repository JuliaManifolds/Manifolds.jl, pull requests merged in 2024-10, with the labels that each got.

#754 Basis number system swap
  NEWS.md
  Project.toml
  ext/ManifoldsTestExt/tests_general.jl
  src/manifolds/Euclidean.jl
  src/manifolds/ProjectiveSpace.jl
  src/manifolds/Symmetric.jl
  src/manifolds/Unitary.jl
  test/manifolds/embedded_torus.jl
  test/manifolds/euclidean.jl
  test/manifolds/projective_space.jl
  test/manifolds/symmetric.jl
  test/manifolds/unitary_matrices.jl
Labels: Ready-for-Review, preview docs

#757 Maybe don't split distributions extension
  .github/workflows/format.yml
  NEWS.md
  Project.toml
  src/Manifolds.jl
Labels: Ready-for-Review, preview docs

#759 Introduce `has_components` for Euclidean
  NEWS.md
  Project.toml
  src/Manifolds.jl
  src/manifolds/Euclidean.jl
  test/ManifoldsTestSuite.jl/ManifoldsTestSuite.jl
  test/manifolds/euclidean.jl
Labels: extend manifold, Ready-for-Review, preview docs

#760 Rewrite contributing.md
  .vale.ini
  CONTRIBUTING.md
  NEWS.md
  docs/styles/Google/AMPM.yml
  docs/styles/Google/Acronyms.yml
  docs/styles/Google/Colons.yml
  docs/styles/Google/Contractions.yml
  docs/styles/Google/DateFormat.yml
  docs/styles/Google/Ellipses.yml
  docs/styles/Google/EmDash.yml
  docs/styles/Google/Exclamation.yml
  docs/styles/Google/FirstPerson.yml
  docs/styles/Google/Gender.yml
  docs/styles/Google/GenderBias.yml
  docs/styles/Google/HeadingPunctuation.yml
  docs/styles/Google/Headings.yml
  docs/styles/Google/Latin.yml
  docs/styles/Google/LyHyphens.yml
  docs/styles/Google/OptionalPlurals.yml
  docs/styles/Google/Ordinal.yml
  docs/styles/Google/OxfordComma.yml
  docs/styles/Google/Parens.yml
  docs/styles/Google/Passive.yml
  docs/styles/Google/Periods.yml
  docs/styles/Google/Quotes.yml
  docs/styles/Google/Ranges.yml
  docs/styles/Google/Semicolons.yml
  docs/styles/Google/Slang.yml
  docs/styles/Google/Spacing.yml
  docs/styles/Google/Spelling.yml
  docs/styles/Google/Units.yml
  docs/styles/Google/We.yml
  docs/styles/Google/Will.yml
  docs/styles/Google/WordList.yml
  docs/styles/Google/meta.json
  docs/styles/Google/vocab.txt
  docs/styles/config/vocabularies/Manifolds/accept.txt
  docs/styles/write-good/Cliches.yml
  docs/styles/write-good/E-Prime.yml
  docs/styles/write-good/Illusions.yml
  docs/styles/write-good/Passive.yml
  docs/styles/write-good/README.md
  docs/styles/write-good/So.yml
  docs/styles/write-good/ThereIs.yml
  docs/styles/write-good/TooWordy.yml
  docs/styles/write-good/Weasel.yml
  docs/styles/write-good/meta.json
  test/approx_inverse_retraction.jl
Labels: Ready-for-Review, discussion

#764 introduce invertible matrices (merely for completeness)
  NEWS.md
  Project.toml
  docs/make.jl
  docs/src/index.md
  docs/src/manifolds/invertible.md
  docs/styles/config/vocabularies/Manifolds/accept.txt
  src/Manifolds.jl
  src/manifolds/InvertibleMatrices.jl
  test/manifolds/invertible_matrices.jl
  test/runtests.jl
Labels: Ready-for-Review, preview docs

#765 New rotation actions
  NEWS.md
  src/Manifolds.jl
  src/groups/rotation_action.jl
  test/groups/rotation_action.jl
Labels: Ready-for-Review, preview docs
